<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:mvc="http://www.springframework.org/schema/mvc"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/context
        http://www.springframework.org/schema/context/spring-context.xsd
        http://www.springframework.org/schema/mvc
        http://www.springframework.org/schema/mvc/spring-mvc.xsd
        http://www.springframework.org/schema/aop
        http://www.springframework.org/schema/aop/spring-aop.xsd">


       <mvc:annotation-driven></mvc:annotation-driven>

       <context:component-scan base-package="com.zyj.controller"/>


       <aop:aspectj-autoproxy proxy-target-class="true"/>


       <!--全局异常
           拦截：无权限时异常，跳转的页面
       -->
      <!-- <bean class="org.springframework.web.servlet.handler.SimpleMappingExceptionResolver">
              <property name="exceptionMappings">
                     <props>
                            <prop key="org.apache.shiro.authz.UnauthorizedException">/refuse.jsp</prop>
                     </props>
              </property>

       </bean>-->
       <bean class="org.springframework.web.servlet.handler.SimpleMappingExceptionResolver">
             <property name="exceptionMappings">
                    <props>
                           <prop key="org.apache.shiro.authz.UnauthorizedException">/refuse.jsp</prop>
                    </props>
             </property>
       </bean>
</beans>